image: maven:3.6-jdk-11

stages:
  - build
  - package

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/

build:
  stage: build
  script:
    - mvn --batch-mode compile

package:
  stage: package
  script:
    - mvn --batch-mode package -DskipTests
  artifacts:
    paths:
